---

language: node_js
node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=e679c1703eebdbf78bc8cce8d90b611df09c55fe8f8e01a347875a250e6079d7

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
